[project]
name = "irrs-lab7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elasticsearch>=8.19.2",
    "elasticsearch-dsl>=8.18.0",
    "mrjob>=0.7.4",
    "numpy>=2.3.5",
]
